const path = require("node:path");
const os = require("node:os");
const fs = require("node:fs");
const fsp = require("node:fs/promises");

const JSZip = require("jszip");

const {
  normalizePath,
  pathExists,
  readJson,
  parseJsonText,
  writeJson,
  writeBytes,
  sha256Hex,
  collectFiles,
  sanitizeRelativePath,
  sanitizeFileToken,
  uniqueDestinationPath,
  backupTimestampDir,
  copyPathToBackupDir,
} = require("./shared.cjs");

const PACK_ARCHIVE_NAME = "pack.rbpack";

function createPackOps(shared, launcherTool) {
  return {
    buildPackPreview,
    writePackArchive,
    readPackPreview,
    importPack,
    dropPackToMod,
    listImportReceipts,
    readInstalledPackSummaries,
    setActiveContentPack,
  };

  async function buildPackPreview(workspace, selection, request) {
    const resolvedSelections = await resolvePackSelections(workspace, selection);
    const contents = resolvedSelections.map((entry) => entry.content);
    const selectionSummary = buildSelectionSummary(contents);

    return {
      packPath: undefined,
      manifest: {
        schemaVersion: 1,
        packId: request.packId?.trim() || slugifyPackId(request.name || "rebalancebap-pack"),
        packVersion: request.packVersion?.trim() || "0.1.0",
        name: request.name?.trim() || "RebalanceBAP Pack",
        description: request.description?.trim() || "",
        author: request.author?.trim() || os.userInfo().username || "RebalanceBAP",
        createdAtUtc: new Date().toISOString(),
        createdWith: launcherTool,
        game: { title: "BAPBAP", compatibleGameVersions: [], compatibleModVersions: [] },
        packageMode: request.packageMode || "delta",
        defaultConflictStrategy: request.defaultConflictStrategy || "replace-targeted-files",
        roots: {
          runtime: selectionSummary.runtimeCount > 0,
          custom: selectionSummary.customCount > 0,
          nativeUi: selectionSummary.nativeUiCount > 0,
          arenaPresets: selectionSummary.arenaPresetCount > 0,
        },
        selectionSummary,
        features: {
          includesRuntimeDocs: selectionSummary.runtimeCount > 0,
          includesCustomAugments: contents.some((entry) => entry.contentRole === "custom-augment"),
          includesCustomIcons: selectionSummary.customIconCount > 0,
          includesAbilitySwaps: selectionSummary.abilitySwapCount > 0,
          includesOperationDocs: selectionSummary.operationDocCount > 0,
          includesNativeUiDocs: selectionSummary.nativeUiCount > 0,
          includesArenaPresets: selectionSummary.arenaPresetCount > 0,
          includesImportReceipts: false,
        },
        contents,
      },
      contents,
      warnings: contents.length ? [] : ["Pick at least one file so the preview has something to export."],
      fileCount: contents.length,
      totalBytes: resolvedSelections.reduce((sum, entry) => sum + entry.bytes.length, 0),
    };
  }

  async function writePackArchive(workspace, outputPath, preview) {
    const zip = new JSZip();
    zip.file("manifest.json", `${JSON.stringify(preview.manifest, null, 2)}\n`);
    zip.file("README.md", `# ${preview.manifest.name}\n\nGenerated by ${launcherTool.tool} ${launcherTool.version}.\n`);

    for (const content of preview.contents) {
      const sourcePath = buildPackPath(workspace, content.root, content.path);
      if (!(await pathExists(sourcePath))) continue;
      zip.file(`${content.root}/${content.path.replace(/\\/g, "/")}`, await fsp.readFile(sourcePath));
    }

    const bytes = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
    await writeBytes(outputPath, bytes);

    return {
      outputPath: normalizePath(outputPath),
      manifest: preview.manifest,
      contents: preview.contents,
      writtenFiles: preview.contents.length,
      writtenBytes: bytes.length,
    };
  }

  async function readPackPreview(packPath) {
    const bytes = await fsp.readFile(packPath);
    const zip = await JSZip.loadAsync(bytes);
    const manifestEntry = zip.file("manifest.json");
    const manifest = manifestEntry
      ? parseJsonText(await manifestEntry.async("text"), normalizePath(packPath))
      : null;
    const contents = manifest?.contents?.length ? manifest.contents : await inferPackContents(zip);

    return {
      packPath: normalizePath(packPath),
      manifest: manifest ?? buildFallbackManifest(packPath, contents),
      contents,
      warnings: [],
      fileCount: contents.length,
      totalBytes: bytes.length,
    };
  }

  async function importPack(workspace, request) {
    const preview = await readPackPreview(request.packPath);
    const conflictStrategy =
      request.conflictStrategy || preview.manifest.defaultConflictStrategy || "replace-targeted-files";
    const createBackup = request.createBackup !== false;
    const zip = await JSZip.loadAsync(await fsp.readFile(request.packPath));
    const warnings = [...preview.warnings];
    const importedAtUtc = new Date().toISOString();
    const backupDir = createBackup ? await backupTimestampDir(workspace, "import") : null;
    const importedFiles = [];

    for (const content of preview.contents) {
      const entry = zip.file(`${content.root}/${content.path.replace(/\\/g, "/")}`);
      if (!entry) {
        warnings.push(`Missing file in pack: ${content.root}/${content.path}`);
        continue;
      }
      const targetPath = buildPackPath(workspace, content.root, content.path);
      const bytes = await entry.async("nodebuffer");
      const targetExists = await pathExists(targetPath);
      const previousSha256 = targetExists ? sha256Hex(await fsp.readFile(targetPath)) : undefined;
      let finalTarget = targetPath;
      let finalBytes = bytes;

      if (conflictStrategy === "skip-existing-files" && targetExists) {
        warnings.push(`Skipped existing file: ${normalizePath(targetPath)}`);
        continue;
      }

      if (conflictStrategy === "import-side-by-side") {
        finalTarget = path.join(
          workspace.importReceiptRoot,
          "SideBySide",
          sanitizeFileToken(preview.manifest.packId),
          sanitizeFileToken(preview.manifest.packVersion),
          content.root,
          sanitizeRelativePath(content.path),
        );
      } else if (conflictStrategy === "merge-json-by-overrides" && targetExists && content.kind === "json") {
        finalBytes = mergeJsonBytes(await fsp.readFile(targetPath), bytes, warnings, targetPath);
      }

      if (backupDir && targetExists && finalTarget === targetPath) {
        await copyPathToBackupDir(workspace, targetPath, backupDir);
      }

      await writeBytes(finalTarget, finalBytes);
      importedFiles.push({
        root: content.root,
        path: content.path,
        targetAbsolutePath: normalizePath(finalTarget),
        previousSha256,
        importedSha256: sha256Hex(finalBytes),
      });
    }

    if (conflictStrategy === "replace-targeted-files" || conflictStrategy === "merge-json-by-overrides") {
      const packRoot = await writeInstalledPackSnapshot(workspace, preview.manifest, request.packPath, importedFiles);
      const nextState = await buildActivePackStateFromSnapshot(
        workspace,
        preview.manifest,
        packRoot,
        request.packPath,
      );
      if (nextState) {
        await applyActivePackState(workspace, nextState);
        await shared.writeActivePackState(workspace, nextState);
      }
    } else {
      warnings.push(
        "Active content pack state was not updated because this import mode does not produce a clean one-pack result.",
      );
    }

    const receipt = {
      packPath: normalizePath(request.packPath),
      manifest: preview.manifest,
      backupPath: backupDir ? normalizePath(backupDir) : null,
      importedAtUtc,
      importedFiles,
      receiptPath: "",
      warnings,
    };
    const receiptPath = await writeImportReceipt(workspace, receipt);
    return { ...receipt, receiptPath };
  }

  async function dropPackToMod(workspace, packPath) {
    const source = path.resolve(packPath);
    if (!(await pathExists(source))) {
      throw new Error("The selected .rbpack file does not exist.");
    }
    const destination = uniqueDestinationPath(workspace.packDropRoot, path.basename(source));
    await fsp.mkdir(path.dirname(destination), { recursive: true });
    await fsp.copyFile(source, destination);
    return { sourcePath: normalizePath(source), destinationPath: normalizePath(destination) };
  }

  async function listImportReceipts(workspace) {
    if (!(await pathExists(workspace.importReceiptRoot))) return [];
    const receipts = [];
    const files = await collectFiles(workspace.importReceiptRoot, true);
    for (const filePath of files) {
      if (!filePath.toLowerCase().endsWith(".json")) continue;
      try {
        const receipt = await readJson(filePath);
        if (!receipt?.manifest?.packId || !receipt?.importedAtUtc) continue;
        receipts.push({
          receiptPath: normalizePath(filePath),
          packId: receipt.manifest.packId,
          packVersion: receipt.manifest.packVersion,
          importedAtUtc: receipt.importedAtUtc,
          importedBy: receipt.manifest.createdWith?.tool ?? launcherTool.tool,
          backupPath: receipt.backupPath ?? null,
          importedFileCount: Array.isArray(receipt.importedFiles) ? receipt.importedFiles.length : 0,
        });
      } catch {
        // ignore malformed receipt
      }
    }
    receipts.sort((left, right) => String(right.importedAtUtc).localeCompare(String(left.importedAtUtc)));
    return receipts;
  }

  async function readInstalledPackSummaries(workspace) {
    if (!(await pathExists(workspace.installedPacksRoot))) return [];
    const activeState = await shared.readActivePackState(workspace);
    const entries = await fsp.readdir(workspace.installedPacksRoot, { withFileTypes: true });
    const summaries = [];

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const packRoot = path.join(workspace.installedPacksRoot, entry.name);
      const manifestPath = path.join(packRoot, "manifest.json");
      if (!(await pathExists(manifestPath))) continue;
      try {
        const manifest = await readJson(manifestPath);
        const contentsRoot = path.join(packRoot, "contents");
        const contentFiles = (await pathExists(contentsRoot)) ? await collectFiles(contentsRoot, true) : [];
        summaries.push({
          packId: manifest.packId,
          packVersion: manifest.packVersion,
          name: manifest.name,
          author: manifest.author,
          packRoot: normalizePath(packRoot),
          archivedPackPath: (await pathExists(path.join(packRoot, PACK_ARCHIVE_NAME)))
            ? normalizePath(path.join(packRoot, PACK_ARCHIVE_NAME))
            : null,
          active: activeState?.packId === manifest.packId,
          activatedAtUtc: activeState?.packId === manifest.packId ? activeState.activatedAtUtc : null,
          contentFileCount: contentFiles.length,
          arenaPresetCount: contentFiles.filter((item) => normalizePath(item).includes("/ArenaPresets/")).length,
        });
      } catch {
        // ignore malformed pack snapshot
      }
    }

    return summaries.sort((left, right) => left.name.localeCompare(right.name, undefined, { sensitivity: "base" }));
  }

  async function setActiveContentPack(workspace, packId) {
    const packRoot = path.join(workspace.installedPacksRoot, sanitizeFileToken(packId));
    const manifestPath = path.join(packRoot, "manifest.json");
    if (!(await pathExists(manifestPath))) {
      throw new Error(`Installed pack '${packId}' was not found.`);
    }

    const manifest = await readJson(manifestPath);
    const archivedPackPath = path.join(packRoot, PACK_ARCHIVE_NAME);
    const nextState = await buildActivePackStateFromSnapshot(
      workspace,
      manifest,
      packRoot,
      await pathExists(archivedPackPath) ? archivedPackPath : null,
    );
    if (nextState) {
      await applyActivePackState(workspace, nextState);
      await shared.writeActivePackState(workspace, nextState);
    }

    const summaries = await readInstalledPackSummaries(workspace);
    const summary = summaries.find((entry) => entry.packId === packId);
    if (!summary) {
      throw new Error(`Installed pack '${packId}' was not found after activation.`);
    }
    return summary;
  }

  async function resolvePackSelections(workspace, selection) {
    const results = [];
    for (const selectedPath of selection) {
      const absolutePath = path.resolve(selectedPath);
      if (!(await pathExists(absolutePath))) continue;
      const location = classifyPackLocation(workspace, absolutePath);
      if (!location) continue;
      const bytes = await fsp.readFile(absolutePath);
      const content = await buildPackContentEntry(absolutePath, location.root, location.relativePath, bytes);
      results.push({ absolutePath, bytes, content });
    }
    return results;
  }

  function classifyPackLocation(workspace, absolutePath) {
    const candidates = [
      { root: "Runtime", base: workspace.runtimeRoot },
      { root: "Custom", base: workspace.customRoot },
      { root: "NativeUI", base: workspace.nativeUiRoot },
      { root: "ArenaPresets", base: workspace.arenaPresetsRoot },
    ];
    const normalizedAbsolute = normalizePath(absolutePath);
    for (const candidate of candidates) {
      if (normalizedAbsolute.startsWith(`${candidate.base}/`) || normalizedAbsolute === candidate.base) {
        return { root: candidate.root, relativePath: normalizedAbsolute.replace(`${candidate.base}/`, "") };
      }
    }
    return null;
  }

  async function buildPackContentEntry(absolutePath, root, relativePath, bytes) {
    const kind = inferPackKind(relativePath);
    const contentRole = inferPackContentRole(root, relativePath, kind);
    return {
      root,
      path: relativePath.replace(/\\/g, "/"),
      kind,
      contentRole,
      sha256: sha256Hex(bytes),
      sizeBytes: bytes.length,
      preview: await buildPackPreviewData(absolutePath, kind, contentRole),
    };
  }

  async function buildPackPreviewData(absolutePath, kind, contentRole) {
    if (kind !== "json") {
      return { title: path.basename(absolutePath), subtitle: contentRole === "custom-icon" ? "Custom icon" : "Workspace file" };
    }
    try {
      const raw = await readJson(absolutePath);
      return {
        title: raw.resolvedName || raw.displayName || raw.label || raw.title || path.basename(absolutePath),
        subtitle: contentRole === "arena-preset-doc"
          ? "Arena preset"
          : contentRole === "native-ui-doc"
            ? "Game Mode / DevArguments file"
            : contentRole === "custom-augment"
              ? "Custom augment"
              : "Runtime document",
        description: raw.cardPreview?.shortDescription || raw.cardPreview?.description || raw.description,
        iconPreviewPath: raw.cardPreview?.iconPreviewPath || raw.cardPreview?.largeCard?.iconPreviewPath,
      };
    } catch {
      return { title: path.basename(absolutePath), subtitle: "Workspace file" };
    }
  }

  function inferPackKind(relativePath) {
    const extension = path.extname(relativePath).toLowerCase();
    if (extension === ".json") return "json";
    if ([".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"].includes(extension)) return "image";
    return extension ? extension.slice(1) : "file";
  }

  function inferPackContentRole(root, relativePath, kind) {
    const normalized = relativePath.replace(/\\/g, "/");
    if (root === "Custom" && normalized.includes("/Icons/")) return "custom-icon";
    if (root === "Custom") return "custom-augment";
    if (root === "ArenaPresets") return "arena-preset-doc";
    if (root === "NativeUI") return "native-ui-doc";
    if (normalized.toLowerCase().endsWith(".operations.json")) return "operation-doc";
    if (normalized.includes("/AbilitySwap")) return "ability-swap-doc";
    if (root === "Runtime" && kind === "json") return "runtime-doc";
    return "runtime-doc";
  }

  async function inferPackContents(zip) {
    const contents = [];
    for (const entry of Object.values(zip.files).filter((item) => !item.dir)) {
      if (entry.name === "manifest.json" || entry.name === "README.md") continue;
      const [root, ...rest] = entry.name.split("/");
      if (!root || !rest.length) continue;
      const relativePath = rest.join("/");
      const bytes = await entry.async("nodebuffer");
      contents.push({
        root,
        path: relativePath,
        kind: inferPackKind(relativePath),
        contentRole: inferPackContentRole(root, relativePath, inferPackKind(relativePath)),
        sha256: sha256Hex(bytes),
        sizeBytes: bytes.length,
        preview: { title: path.basename(relativePath), subtitle: "Imported file" },
      });
    }
    return contents;
  }

  async function writeInstalledPackSnapshot(workspace, manifest, packPath, importedFiles) {
    const packRoot = path.join(workspace.installedPacksRoot, sanitizeFileToken(manifest.packId));
    await fsp.rm(packRoot, { recursive: true, force: true });
    await fsp.mkdir(packRoot, { recursive: true });
    await fsp.copyFile(packPath, path.join(packRoot, PACK_ARCHIVE_NAME));
    await writeJson(path.join(packRoot, "manifest.json"), manifest);
    for (const file of importedFiles) {
      const destination = path.join(packRoot, "contents", file.root, sanitizeRelativePath(file.path));
      await fsp.mkdir(path.dirname(destination), { recursive: true });
      await fsp.copyFile(file.targetAbsolutePath, destination);
      if (isManagedPackRoot(file.root)) {
        const liveDestination = path.join(packRoot, "Live", file.root, sanitizeRelativePath(file.path));
        await fsp.mkdir(path.dirname(liveDestination), { recursive: true });
        await fsp.copyFile(file.targetAbsolutePath, liveDestination);
      }
    }
    return packRoot;
  }

  async function writeImportReceipt(workspace, receipt) {
    const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
    const fileName = `${timestamp}_${sanitizeFileToken(receipt.manifest.packId)}.json`;
    const receiptPath = path.join(workspace.importReceiptRoot, fileName);
    await writeJson(receiptPath, receipt);
    return normalizePath(receiptPath);
  }

  function buildPackPath(workspace, root, relativePath) {
    const sanitized = sanitizeRelativePath(relativePath);
    if (root === "Runtime") return path.join(workspace.runtimeRoot, sanitized);
    if (root === "Custom") return path.join(workspace.customRoot, sanitized);
    if (root === "NativeUI") return path.join(workspace.nativeUiRoot, sanitized);
    if (root === "ArenaPresets") return path.join(workspace.arenaPresetsRoot, sanitized);
    throw new Error(`Unsupported pack root '${root}'.`);
  }

  function isManagedPackRoot(root) {
    return root === "Runtime" || root === "Custom" || root === "NativeUI";
  }

  async function buildActivePackStateFromSnapshot(workspace, manifest, packRoot, archivedPackPath) {
    const managedFiles = [];
    const liveRoot = path.join(packRoot, "Live");

    for (const rootName of ["Runtime", "Custom", "NativeUI"]) {
      const rootPath = path.join(liveRoot, rootName);
      if (!(await pathExists(rootPath))) {
        continue;
      }

      const files = await collectFiles(rootPath, true);
      for (const filePath of files) {
        const relativePath = path.relative(rootPath, filePath).replace(/\\/g, "/");
        const targetPath = buildPackPath(workspace, rootName, relativePath);
        const bytes = await fsp.readFile(filePath);
        managedFiles.push({
          root: rootName,
          relativePath,
          snapshotPath: normalizePath(filePath),
          targetAbsolutePath: normalizePath(targetPath),
          sha256: sha256Hex(bytes),
        });
      }
    }

    if (!managedFiles.length) {
      return null;
    }

    return {
      schemaVersion: 1,
      packId: manifest.packId,
      packVersion: manifest.packVersion,
      archivedPackPath: archivedPackPath ? normalizePath(archivedPackPath) : null,
      activatedAtUtc: new Date().toISOString(),
      managedFiles,
    };
  }

  async function cleanupInactiveManagedFiles(previousState, nextState) {
    if (!previousState?.managedFiles?.length) {
      return;
    }

    const nextKeys = new Set(
      nextState.managedFiles.map((file) => `${String(file.root).toLowerCase()}/${String(file.relativePath).toLowerCase()}`),
    );

    for (const previousFile of previousState.managedFiles) {
      const key = `${String(previousFile.root).toLowerCase()}/${String(previousFile.relativePath).toLowerCase()}`;
      if (nextKeys.has(key)) {
        continue;
      }
      if (previousFile.targetAbsolutePath && await pathExists(previousFile.targetAbsolutePath)) {
        await fsp.rm(previousFile.targetAbsolutePath, { force: true });
      }
    }
  }

  async function applyActivePackState(workspace, nextState) {
    const previousState = await shared.readActivePackState(workspace);
    await cleanupInactiveManagedFiles(previousState, nextState);

    for (const managedFile of nextState.managedFiles) {
      if (!(await pathExists(managedFile.snapshotPath))) {
        continue;
      }

      if (await pathExists(managedFile.targetAbsolutePath)) {
        const currentSha = sha256Hex(await fsp.readFile(managedFile.targetAbsolutePath));
        if (currentSha === managedFile.sha256) {
          continue;
        }
      }

      await writeBytes(managedFile.targetAbsolutePath, await fsp.readFile(managedFile.snapshotPath));
    }
  }

  function buildFallbackManifest(packPath, contents) {
    const selectionSummary = buildSelectionSummary(contents);
    return {
      schemaVersion: 1,
      packId: slugifyPackId(path.basename(packPath, path.extname(packPath))),
      packVersion: "0.1.0",
      name: path.basename(packPath, path.extname(packPath)),
      description: "",
      author: launcherTool.tool,
      createdAtUtc: new Date().toISOString(),
      createdWith: launcherTool,
      game: { title: "BAPBAP", compatibleGameVersions: [], compatibleModVersions: [] },
      packageMode: "delta",
      defaultConflictStrategy: "replace-targeted-files",
      roots: {
        runtime: selectionSummary.runtimeCount > 0,
        custom: selectionSummary.customCount > 0,
        nativeUi: selectionSummary.nativeUiCount > 0,
        arenaPresets: selectionSummary.arenaPresetCount > 0,
      },
      selectionSummary,
      features: {
        includesRuntimeDocs: selectionSummary.runtimeCount > 0,
        includesCustomAugments: contents.some((entry) => entry.contentRole === "custom-augment"),
        includesCustomIcons: selectionSummary.customIconCount > 0,
        includesAbilitySwaps: selectionSummary.abilitySwapCount > 0,
        includesOperationDocs: selectionSummary.operationDocCount > 0,
        includesNativeUiDocs: selectionSummary.nativeUiCount > 0,
        includesArenaPresets: selectionSummary.arenaPresetCount > 0,
        includesImportReceipts: false,
      },
      contents,
    };
  }

  function buildSelectionSummary(contents) {
    return {
      runtimeCount: contents.filter((entry) => entry.root === "Runtime").length,
      customCount: contents.filter((entry) => entry.root === "Custom").length,
      nativeUiCount: contents.filter((entry) => entry.root === "NativeUI").length,
      arenaPresetCount: contents.filter((entry) => entry.root === "ArenaPresets").length,
      abilitySwapCount: contents.filter((entry) => entry.contentRole === "ability-swap-doc").length,
      operationDocCount: contents.filter((entry) => entry.contentRole === "operation-doc").length,
      customIconCount: contents.filter((entry) => entry.contentRole === "custom-icon").length,
      importReceiptCount: 0,
    };
  }

  function mergeJsonBytes(existingBytes, incomingBytes, warnings, targetPath) {
    const merged = mergeJsonValues(
      JSON.parse(existingBytes.toString("utf8").replace(/^\uFEFF/, "")),
      JSON.parse(incomingBytes.toString("utf8").replace(/^\uFEFF/, "")),
    );
    warnings.push(`Merged JSON overrides into ${normalizePath(targetPath)}`);
    return Buffer.from(`${JSON.stringify(merged, null, 2)}\n`, "utf8");
  }

  function mergeJsonValues(existing, incoming) {
    if (existing && incoming && typeof existing === "object" && typeof incoming === "object"
      && !Array.isArray(existing) && !Array.isArray(incoming)) {
      const result = { ...existing };
      for (const [key, value] of Object.entries(incoming)) {
        result[key] = key in result ? mergeJsonValues(result[key], value) : value;
      }
      return result;
    }
    return incoming;
  }

  function slugifyPackId(name) {
    return String(name).trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "rebalancebap-pack";
  }
}

module.exports = {
  createPackOps,
};
